name: Run Python Script

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load environment variables from .env
        run: |
          echo "Loading environment variables from .env file"
          set -a
          source .env
          set +a

      - name: Run vehicle_mapping.py
        run: python vehicle_mapping.py
